#!/bin/bash

profile_id="$1"
profile_name="$2"
reason="$3"
errorcode="$4"
vmxml="$HOME/.config/system/libvirt"


case $reason in
    1)
        mkdir -p $vmxml
        for vm in $(virsh list --all --name)
        do
           virsh dumpxml $vm > "$vmxml/$vm.xml"
        done

        copy samba config if newer
        cp -u /etc/samba/smb.conf $HOME/.config/system/smb.conf
esac
